name: Deploy to EC2 (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
            
            echo "📂 Navigating to project folder..."
            cd repos/quixent-api/   # 🔥 

            echo "📥 Pulling latest code..."
            git pull origin main

            echo "🐳 Running deploy script..."
            chmod +x deploy.sh
            ./deploy.sh

          EOF

      - name: Cleanup
        run: rm -f key.pem